### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by nfinitedesign** [nfinitedesign/dmfk2022#1]
Wir werden aktuell bei einer Google Suche nicht gefunden, wie wird sowas eingerichtet?

**Comment by m-schwald** [comment]
Hm, von SEO hab ich echt so gar keinen Plan. Aber da müsste es doch auch ne Youtube-Geschichte geben, die die gröbsten Sachen abdeckt und damit für unseren Fall ausreichend wäre.

**Comment by nfinitedesign** [comment]
hab grad bei der ssl umstellung dazu was bei meinem webhoster gefunden ... seo machen die für 30€ .... frag mich ob das immer was kostet ... klingt erst mal nicht super teuer ...

**Comment by nfinitedesign** [comment]
war eigentlich recht einfach im endeffekt ... done
