### ISSUE TITLE
Dimensionen Karte

### ISSUE THREAD

**Issue by nfinitedesign** [nfinitedesign/dmfk2022#2]
Wie legt man die Dimensionen vom iframe so fest, dass sie mit dem DIV vom Template übereinstimmen und dynamisch sind? Aktuell mache ichs mit width=640px; height=480px; ... denke das ist suboptimal

**Comment by nfinitedesign** [comment]
HM irgendwie kriege ich's net hin ... und nun is die Karte auch noch weg wenn man auf mobile umschaltet :(

**Comment by m-schwald** [comment]
Hm, das hatte ich grade heute auf Arbeit. Es gibt den iFrame-Resizer, der die Größe des iFrames an seinen Inhalt anpasst. Ich muss mir das aber mal genauer anschauen, ob das wirklich benötigt wird. 
Alternativ kannst du dem iFrame ne Klasse geben und die dann in CSS dynamisch vergrößern / verkleinern. zB: width = calc(100vw - 20px)
so bist du auf der kompletten Bildschirmbreite abzüglich eines kleinen Rands...

**Comment by nfinitedesign** [comment]
is aber n div und kein iframe ... wenn du das grad gemacht hast, kannst du dir das voll mal anschauen und vllt umsetzen? mit statischer größe von zb 640px siehts auch eigentlich ok aus und is auch auf mobile sichtbar, nur die position is hässlich ...
