### ISSUE TITLE
Umstellung auf HTTPS?

### ISSUE THREAD

**Issue by nfinitedesign** [nfinitedesign/dmfk2022#6]
Was brauchen wir dafür? Is sowas easy umsetzbar?

**Comment by m-schwald** [comment]
Brauchen wir auf jeden Fall. Bei meinem Server ist das so ne 1-Klick-Nummer, da bestellt ich einfach ein SSL-Zertifikat über let's encrypt und dann passt alles. Bei der erogenen Zone hatte ich damit bisschen mehr Stress, weil sich das Zertifikat nicht automatisch verlängern wollte. Aber insgesamt ist das nicht der große Stress

**Comment by nfinitedesign** [comment]
ok das war echt relativ easy ...
