### ISSUE TITLE
Datenschutz / Impressum

### ISSUE THREAD

**Issue by nfinitedesign** [nfinitedesign/dmfk2022#7]
Hab ich NULL Ahnung von .... wer kann sowas machen?

**Comment by m-schwald** [comment]
Das ist eigentlich recht einfach, ich hab das immer über https://www.e-recht24.de/ gemacht. Geht auch wo anders, gibt so Datenschutz-Generatoren. 
Die Seite hat ja keine große Datenverarbeitung oder schickt persönlichen Kram in die USA... Klick dich da einfach mal durch.

**Comment by nfinitedesign** [comment]
ja das einzige was ich da nicht gefunden habe is irgendwas zu pretix ... und das ticketsystem speichert ja auf jeden fall daten auf unserem server, denke das muss schon irgendwie rein aber keine ahnung wie ..

**Comment by nfinitedesign** [comment]
hab jetzt was von adsimple generieren lassen ... hoffe mal das passt so, vor allem wg pretix
