### ISSUE TITLE
keine scrollbar mehr

### ISSUE THREAD

**Issue by nfinitedesign** [nfinitedesign/dmfk2022#8]
keeeine ahnung was da los is ... wo ist sie hin und wie kriegt man sie wieder?

**Comment by bwnstck** [comment]
Wo siehst du die scrollbar nicht? Ich hab eine unter chrome/firefox :)

**Comment by nfinitedesign** [comment]
hääää bei mir in brave hab ich keine ... naja is eh n nischenbrowser, also auch egal solang es bei den anderen geht
